spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql:///book?serverTimezone=UTC
mybatis:
    mapper-locations: classpath:mapper/*.xml
logging:
    level:
      com:
        book:
          app:
            dao: debug
server:
  port: 7514